name: mozilla-central Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
    - cron: "0 8 * * *"
    - cron: "0 14 * * *"
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Git configuration
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Execute version update
        run: |
          cd automation
          npm install
          npm run start | tee >(grep '^NEW_VERSION=' >> $GITHUB_ENV)

      - name: Push version to GitHub
        id: github-push
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Firefox Nightly $NEW_VERSION"
          git push

      - name: Failed to push version
        if: ${{ failure() && steps.github-push.conclusion == 'failure' }}
        run: echo Failed to update version or version already at latest
